"""
Drift-Sense: Train Siamese Network from Pre-Generated Triplets
===============================================================
Step 2 of 2 for Offline Training.

Reads anchor/positive/negative PNGs from disk (generated by generate_triplets.py)
and trains the SiameseRanker at full GPU speed with zero CPU bottleneck.

Loss matches DEPLOYMENT exactly: localize.py ranks candidates by cosine
similarity of L2-normalized embeddings. We therefore optimize the cosine
triplet margin -- sim(a,p) > sim(a,n) + margin -- and report the share where
the positive actually out-scores the (hard-mined, NCC-confusable) negative.

Usage:
    python train_offline.py --train-dir training_data --val-dir training_data_val --epochs 30
"""

import argparse
import os
import json
import glob
import time

import numpy as np
from PIL import Image
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingWarmRestarts

from siamese_net import SiameseRanker, export_to_onnx


class DiskTripletDataset(Dataset):
    """
    Reads pre-generated triplet PNGs from disk.
    Expected directory structure:
        data_dir/
            anchors/00000.png, 00001.png, ...
            positives/00000.png, 00001.png, ...
            negatives/00000.png, 00001.png, ...
    """

    def __init__(self, data_dir):
        self.anchor_dir = os.path.join(data_dir, 'anchors')
        self.positive_dir = os.path.join(data_dir, 'positives')
        self.negative_dir = os.path.join(data_dir, 'negatives')

        self.files = sorted(glob.glob(os.path.join(self.anchor_dir, '*.png')))
        if not self.files:
            raise FileNotFoundError(
                f"No anchor PNGs found in {self.anchor_dir}. "
                f"Run generate_triplets.py first."
            )
        print(f"  Loaded {len(self.files)} triplets from {data_dir}")

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        fname = os.path.basename(self.files[idx])

        anchor = np.array(
            Image.open(os.path.join(self.anchor_dir, fname)),
            dtype=np.float32
        ) / 255.0
        positive = np.array(
            Image.open(os.path.join(self.positive_dir, fname)),
            dtype=np.float32
        ) / 255.0
        negative = np.array(
            Image.open(os.path.join(self.negative_dir, fname)),
            dtype=np.float32
        ) / 255.0

        a = torch.from_numpy(anchor).unsqueeze(0)
        p = torch.from_numpy(positive).unsqueeze(0)
        n = torch.from_numpy(negative).unsqueeze(0)

        return a, p, n


def cos_triplet_loss(emb_a, emb_p, emb_n, margin=0.2):
    """Cosine-similarity triplet loss.

    Embeddings are L2 normalized by the encoder, so similarity == dot product.
    This is exactly the quantity rank_candidates() uses at deployment, so we
    minimize relu(sim(a,n) - sim(a,p) + margin).
    """
    sim_p = (emb_a * emb_p).sum(dim=1)
    sim_n = (emb_a * emb_n).sum(dim=1)
    return F.relu(sim_n - sim_p + margin).mean()


@torch.no_grad()
def evaluate(model, loader, device, margin=0.2):
    """Return (rank_acc) and (margin_acc) over the loader.

    rank_acc:  share where sim(a,pos) > sim(a,neg)
    margin_acc: share where sim(a,pos) > sim(a,neg) + margin -- a proxy for the
                deployment relative-margin gate (rel_margin >= 1%)
    """
    model.eval()
    rank_correct = 0
    margin_correct = 0
    total = 0

    for a, p, n in loader:
        a, p, n = a.to(device), p.to(device), n.to(device)
        emb_a = model(a)
        emb_p = model(p)
        emb_n = model(n)

        sim_p = (emb_a * emb_p).sum(dim=1)
        sim_n = (emb_a * emb_n).sum(dim=1)

        rank_correct += (sim_p > sim_n).sum().item()
        margin_correct += (sim_p > sim_n + margin).sum().item()
        total += a.size(0)

    return (rank_correct / total, margin_correct / total) if total else (0.0, 0.0)


def main():
    parser = argparse.ArgumentParser(
        description="Train Siamese Ranker from pre-generated triplets"
    )
    parser.add_argument('--train-dir', type=str, default='training_data',
                        help="Directory with training triplets")
    parser.add_argument('--val-dir', type=str, default='training_data_val',
                        help="Directory with validation triplets")
    parser.add_argument('--epochs', type=int, default=30,
                        help="Number of epochs")
    parser.add_argument('--lr', type=float, default=0.001,
                        help="Learning rate")
    parser.add_argument('--margin', type=float, default=0.2,
                        help="Cosine triplet margin")
    parser.add_argument('--batch-size', type=int, default=64,
                        help="Batch size")
    args = parser.parse_args()

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Device: {device}")
    print(f"Config: epochs={args.epochs}, lr={args.lr}, "
          f"margin={args.margin}, batch={args.batch_size}")

    os.makedirs('weights', exist_ok=True)

    print("\nLoading datasets from disk...")
    train_dataset = DiskTripletDataset(args.train_dir)
    val_dataset = DiskTripletDataset(args.val_dir)

    train_loader = DataLoader(
        train_dataset, batch_size=args.batch_size,
        shuffle=True, num_workers=2, pin_memory=True
    )
    val_loader = DataLoader(
        val_dataset, batch_size=args.batch_size,
        shuffle=False, num_workers=2, pin_memory=True
    )

    model = SiameseRanker().to(device)
    param_count = sum(p.numel() for p in model.parameters())
    print(f"Model parameters: {param_count:,}")

    optimizer = AdamW(model.parameters(), lr=args.lr, weight_decay=1e-4)
    scheduler = CosineAnnealingWarmRestarts(
        optimizer, T_0=10, T_mult=2, eta_min=1e-6
    )

    best_margin_acc = 0.0
    patience_counter = 0
    patience = 20
    warmup_epochs = 3
    training_log = []

    print(f"\n{'='*60}")
    print(f"Starting training: {len(train_dataset)} train, "
          f"{len(val_dataset)} val")
    print(f"{'='*60}\n")

    total_start = time.time()

    for epoch in range(args.epochs):
        epoch_start = time.time()

        if epoch < warmup_epochs:
            lr = args.lr * ((epoch + 1) / warmup_epochs)
            for param_group in optimizer.param_groups:
                param_group['lr'] = lr

        model.train()
        train_loss = 0.0
        train_correct = 0
        train_total = 0

        for a, p, n in train_loader:
            a, p, n = a.to(device), p.to(device), n.to(device)

            optimizer.zero_grad()
            emb_a = model(a)
            emb_p = model(p)
            emb_n = model(n)

            loss = cos_triplet_loss(emb_a, emb_p, emb_n, args.margin)
            loss.backward()

            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            train_loss += loss.item() * a.size(0)
            train_correct += ((emb_a * emb_p).sum(dim=1) > (emb_a * emb_n).sum(dim=1)).sum().item()
            train_total += a.size(0)

        if epoch >= warmup_epochs:
            scheduler.step()

        train_loss /= len(train_dataset) if len(train_dataset) else 1
        train_acc = train_correct / train_total if train_total else 0.0
        val_rank_acc, val_margin_acc = evaluate(model, val_loader, device, args.margin)
        epoch_time = time.time() - epoch_start

        current_lr = optimizer.param_groups[0]['lr']

        print(f"Epoch {epoch+1:3d}/{args.epochs} | "
              f"Loss: {train_loss:.5f} | "
              f"Train Acc: {train_acc:.4f} | "
              f"Val Rank: {val_rank_acc:.4f} | "
              f"Val Margin: {val_margin_acc:.4f} | "
              f"LR: {current_lr:.2e} | "
              f"Time: {epoch_time:.1f}s")

        training_log.append({
            'epoch': epoch + 1,
            'train_loss': train_loss,
            'train_acc': train_acc,
            'val_rank_acc': val_rank_acc,
            'val_margin_acc': val_margin_acc,
            'lr': current_lr,
            'time_s': epoch_time,
        })

        if val_margin_acc > best_margin_acc:
            best_margin_acc = val_margin_acc
            torch.save(model.state_dict(), 'weights/siamese_ranker.pth')
            patience_counter = 0
            print(f"  >>> Best model saved (margin_acc={val_margin_acc:.4f})")
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print(f"Early stopping at epoch {epoch+1}")
                break

    total_time = time.time() - total_start
    print(f"\n{'='*60}")
    print(f"Training complete in {total_time:.1f}s ({total_time/60:.1f} min)")
    print(f"Best validation margin accuracy: {best_margin_acc:.4f}")
    print(f"{'='*60}")

    with open('weights/training_log.json', 'w') as f:
        json.dump(training_log, f, indent=2)

    if os.path.exists('weights/siamese_ranker.pth'):
        model.load_state_dict(
            torch.load('weights/siamese_ranker.pth',
                        map_location=device, weights_only=False)
        )
        print(f"\nLoaded best model (margin_acc={best_margin_acc:.4f})")

    export_to_onnx(model, 'weights/siamese_ranker.onnx')
    print("Exported to weights/siamese_ranker.onnx")
    print("\nDone! Run 'python benchmark.py' to see the AI improvement.")


if __name__ == '__main__':
    main()